[[libseccomp]]
arch = "aarch64"
git-tree-sha1 = "1c568e961ed100b27660cdd52ba1d43e4fcc699e"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "d684a41ae29f4fbc331a1f77ca0c91a23b7ba2b4534e03a15206e13d9a86b07a"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.4+0/libseccomp.v2.5.4.aarch64-linux-gnu.tar.gz"
[[libseccomp]]
arch = "aarch64"
git-tree-sha1 = "4eddf873ba81a9f04d6f03e08148048c2e1d0e08"
libc = "musl"
os = "linux"

    [[libseccomp.download]]
    sha256 = "869e7cd772a0cc7abf57f925112f13dad46f31204cece52c3dfbbaf67c8ba03e"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.4+0/libseccomp.v2.5.4.aarch64-linux-musl.tar.gz"
[[libseccomp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dbedae8946fd005eb8f626746dc667a9500ce314"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "5f52636d7a4b8e21bbab32a7215659194305776caa94c0aaf61242a690c83d91"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.4+0/libseccomp.v2.5.4.armv6l-linux-gnueabihf.tar.gz"
[[libseccomp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6ff1991e0ce65e00a3451b5483e41ad8fdf39b7c"
libc = "musl"
os = "linux"

    [[libseccomp.download]]
    sha256 = "c5db87afcb64c5401596c2c311dcb9ae96a923171450bcc0a3bb389fac364180"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.4+0/libseccomp.v2.5.4.armv6l-linux-musleabihf.tar.gz"
[[libseccomp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "23ee38bc70b1d1cfa3210531fdc6a1690ab542d0"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "6258da5c426f358267cd88e82fae5d1e349ac78cdcf2f64b330cd09a24b7b616"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.4+0/libseccomp.v2.5.4.armv7l-linux-gnueabihf.tar.gz"
[[libseccomp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "898235074724583a1055b85fbe87ac165cf38c18"
libc = "musl"
os = "linux"

    [[libseccomp.download]]
    sha256 = "652ed132d53afb770d2f08476b39924e6191eb62a8922a27dd89d35054d4a07b"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.4+0/libseccomp.v2.5.4.armv7l-linux-musleabihf.tar.gz"
[[libseccomp]]
arch = "i686"
git-tree-sha1 = "79a61255dbcf7cd12de1860954d39891fbfa8fbf"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "27c6c7678084382ca8644d0a514e28715ea2c641901e2dfcb2d6fb9e34c646ea"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.4+0/libseccomp.v2.5.4.i686-linux-gnu.tar.gz"
[[libseccomp]]
arch = "i686"
git-tree-sha1 = "b374cb7cf1d3c2cda9c28c96bd7aba7d7b1672a1"
libc = "musl"
os = "linux"

    [[libseccomp.download]]
    sha256 = "9b4180bd127359b32543be76c8cdc12ff0ad7290149b003a630e5221a34075e7"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.4+0/libseccomp.v2.5.4.i686-linux-musl.tar.gz"
[[libseccomp]]
arch = "powerpc64le"
git-tree-sha1 = "03ef58a1e1b89b109a65900d7c9353f460b584a7"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "5fec1673f6970ba8c5a1053b666f205d9bf11a263afd44aab1f4dd9a106f692b"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.4+0/libseccomp.v2.5.4.powerpc64le-linux-gnu.tar.gz"
[[libseccomp]]
arch = "x86_64"
git-tree-sha1 = "d7f343f79a558bec4e15770f819cd7bd003f6244"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "93d4a91f873dc99ae7a91344cdd1bfe5622b51e0656cd8a310b35f3c82b64e9a"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.4+0/libseccomp.v2.5.4.x86_64-linux-gnu.tar.gz"
[[libseccomp]]
arch = "x86_64"
git-tree-sha1 = "b4d4d910a8b797020908d25545a37f471d6f3955"
libc = "musl"
os = "linux"

    [[libseccomp.download]]
    sha256 = "ec2b2fcc5fdd7f58893126af9017a4ab690ec38d69dd443d0b666554fd1219f8"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.4+0/libseccomp.v2.5.4.x86_64-linux-musl.tar.gz"
