[[libseccomp]]
arch = "aarch64"
git-tree-sha1 = "4a03505a9a8eb3b121142fa808d5d3e0918a81b3"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "9d378346f5d48c79d1b072759724d6aa646efd2602013642cdb9b0b61717c74a"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.5+0/libseccomp.v2.5.5.aarch64-linux-gnu.tar.gz"
[[libseccomp]]
arch = "aarch64"
git-tree-sha1 = "8f398a8c473ea551c5067f9de535f654c8be0c73"
libc = "musl"
os = "linux"

    [[libseccomp.download]]
    sha256 = "827eb9bc0b634b52c366b32cb037509f58f053539b7120ecbaa6520eb2be3b99"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.5+0/libseccomp.v2.5.5.aarch64-linux-musl.tar.gz"
[[libseccomp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "946f6267a235fa9ce808890cfcc73d4ea863c217"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "e2f87f410453c0fde3206c078571c6f2bb0884ded1238b7cac84b9bd51f71a2c"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.5+0/libseccomp.v2.5.5.armv6l-linux-gnueabihf.tar.gz"
[[libseccomp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e603e70bcd192edd0215752931fe5ace4b16026b"
libc = "musl"
os = "linux"

    [[libseccomp.download]]
    sha256 = "5df0a5ce8d83acbb212bb7df26489ddea1e9e431c8c605df1a174298c241893e"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.5+0/libseccomp.v2.5.5.armv6l-linux-musleabihf.tar.gz"
[[libseccomp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b50b0c64f5bd835dd49c4cd203549547bda37ec"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "1b49e4602eb6c9d5cd95e70755358ae8522255434ddda84b570b625d068506a4"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.5+0/libseccomp.v2.5.5.armv7l-linux-gnueabihf.tar.gz"
[[libseccomp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f5b7fdb4b68ecd92bce4363c28ef00d1ffac2507"
libc = "musl"
os = "linux"

    [[libseccomp.download]]
    sha256 = "b4ba643aa09a0acd844169257da450d7c1a425505f6582ca81316def5367298b"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.5+0/libseccomp.v2.5.5.armv7l-linux-musleabihf.tar.gz"
[[libseccomp]]
arch = "i686"
git-tree-sha1 = "fa87a72de0a5f854d384a9a072cc58bfebb0f1af"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "c1b305f6f559aac1b72f708b0a4e5511e70e27addb5841a2bec194c87aa4d1e6"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.5+0/libseccomp.v2.5.5.i686-linux-gnu.tar.gz"
[[libseccomp]]
arch = "i686"
git-tree-sha1 = "8f893b7254dc1a4bcde5c4997cb4ba6c7548c8c5"
libc = "musl"
os = "linux"

    [[libseccomp.download]]
    sha256 = "97184ee5a69558d517b6c7cbd0306d25ff2a7bf9b4b4d5235495803bd6004e63"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.5+0/libseccomp.v2.5.5.i686-linux-musl.tar.gz"
[[libseccomp]]
arch = "powerpc64le"
git-tree-sha1 = "430abb2bfa33459f7000181176b63e97f0a2b144"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "b572fdd82b765181186d8d8d5798ce4cdb27dbbe3faece5ae7c9b6474b64c534"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.5+0/libseccomp.v2.5.5.powerpc64le-linux-gnu.tar.gz"
[[libseccomp]]
arch = "x86_64"
git-tree-sha1 = "d4b83da3ec60378f1930407c1acbb494671c2266"
libc = "glibc"
os = "linux"

    [[libseccomp.download]]
    sha256 = "1e46f4f76eb89596064f28852e7f3182b95a6c8d9301fece098135041ac7f2c9"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.5+0/libseccomp.v2.5.5.x86_64-linux-gnu.tar.gz"
[[libseccomp]]
arch = "x86_64"
git-tree-sha1 = "c18a753087fec282c10a583a0c670b4995dbe3fc"
libc = "musl"
os = "linux"

    [[libseccomp.download]]
    sha256 = "13c459357cae480ea432e984e3f1ff5a1e047b7a5a97dfd7e94ff790a0872a66"
    url = "https://github.com/JuliaBinaryWrappers/libseccomp_jll.jl/releases/download/libseccomp-v2.5.5+0/libseccomp.v2.5.5.x86_64-linux-musl.tar.gz"
